### ISSUE TITLE
youtube search error

### ISSUE THREAD

**Issue by Unknown700** [Discord-Bot-Maker-Mods/DBM-Mods#186]
I was making my music command and it all worked fine until an unexpected error happened. It just made the music command or more specificly the youtube-search action completly break. Evtything worked fine until the error came upp. Heres the DBM log.
![Screenshot_10](https://user-images.githubusercontent.com/41698989/58518689-747bac00-81b0-11e9-87d6-9fef61571b8a.png)

**Comment by Unknown700** [comment]
also hwne I tryed the command now my built in error tracker got this

Error with Event "YouTube Search", Action #14
Error: Cannot find module 'youtube-search'
at Function.Module._resolveFilename (module.js:567:15)
at Function.Module._load (module.js:492:25)
at Module.require (module.js:610:17)
at Object.WrexMODS.require (C:\Program Files (x86)\Steam\steamapps\common\Discord Bot Maker\actions\aaa_wrexmods_dependencies_MOD.js:148:22)
at Object.action [as YouTube Search] (C:\Program Files (x86)\Steam\steamapps\common\Discord Bot Maker\actions\youtube_search_MOD.js:227:27)
at Object.Actions.callNextAction (D:\Bots\Coolbot[Beta version]\bot.js:493:18)
at Object.<anonymous> (C:\Program Files (x86)\Steam\steamapps\common\Discord Bot Maker\actions\send_message.js:167:9)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)

Don't know if it will help but here it is anyways

**Comment by SeikiMatt** [comment]
This is a common issue with a known fix, the people in #support can help.
