### ISSUE TITLE
Error: FFMPEG not found

### ISSUE THREAD

**Issue by YordiYVE** [Discord-Bot-Maker-Mods/DBM-Mods#200]
`2019-07-02T19:34:43.765006+00:00 app[worker.1]: Error: FFMPEG not found
2019-07-02T19:34:43.765044+00:00 app[worker.1]:     at Function.selectFfmpegCommand (/app/node_modules/prism-media/src/transcoders/ffmpeg/Ffmpeg.js:46:13)
2019-07-02T19:34:43.765046+00:00 app[worker.1]:     at new FfmpegTranscoder (/app/node_modules/prism-media/src/transcoders/ffmpeg/Ffmpeg.js:7:37)
2019-07-02T19:34:43.765047+00:00 app[worker.1]:     at new MediaTranscoder (/app/node_modules/prism-media/src/transcoders/MediaTranscoder.js:10:19)
2019-07-02T19:34:43.765049+00:00 app[worker.1]:     at new Prism (/app/node_modules/prism-media/src/Prism.js:5:23)
2019-07-02T19:34:43.765050+00:00 app[worker.1]:     at new VoiceConnection (/app/node_modules/discord.js/src/client/voice/VoiceConnection.js:46:18)
2019-07-02T19:34:43.765052+00:00 app[worker.1]:     at Promise (/app/node_modules/discord.js/src/client/voice/ClientVoiceManager.js:63:22)
2019-07-02T19:34:43.765054+00:00 app[worker.1]:     at new Promise (<anonymous>)
2019-07-02T19:34:43.765056+00:00 app[worker.1]:     at ClientVoiceManager.joinChannel (/app/node_modules/discord.js/src/client/voice/ClientVoiceManager.js:45:12)
2019-07-02T19:34:43.765057+00:00 app[worker.1]:     at VoiceChannel.join (/app/node_modules/discord.js/src/structures/VoiceChannel.js:130:30)
2019-07-02T19:34:43.765059+00:00 app[worker.1]:     at Object.Audio.connectToVoice (/app/bot.js:1414:31)
2019-07-02T19:34:43.765877+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Error: FFMPEG not found
2019-07-02T19:34:43.765878+00:00 app[worker.1]:     at Function.selectFfmpegCommand (/app/node_modules/prism-media/src/transcoders/ffmpeg/Ffmpeg.js:46:13)
2019-07-02T19:34:43.765880+00:00 app[worker.1]:     at new FfmpegTranscoder (/app/node_modules/prism-media/src/transcoders/ffmpeg/Ffmpeg.js:7:37)
2019-07-02T19:34:43.765881+00:00 app[worker.1]:     at new MediaTranscoder (/app/node_modules/prism-media/src/transcoders/MediaTranscoder.js:10:19)
2019-07-02T19:34:43.765882+00:00 app[worker.1]:     at new Prism (/app/node_modules/prism-media/src/Prism.js:5:23)
2019-07-02T19:34:43.765884+00:00 app[worker.1]:     at new VoiceConnection (/app/node_modules/discord.js/src/client/voice/VoiceConnection.js:46:18)
2019-07-02T19:34:43.765885+00:00 app[worker.1]:     at Promise (/app/node_modules/discord.js/src/client/voice/ClientVoiceManager.js:63:22)
2019-07-02T19:34:43.765886+00:00 app[worker.1]:     at new Promise (<anonymous>)
2019-07-02T19:34:43.765888+00:00 app[worker.1]:     at ClientVoiceManager.joinChannel (/app/node_modules/discord.js/src/client/voice/ClientVoiceManager.js:45:12)
2019-07-02T19:34:43.765889+00:00 app[worker.1]:     at VoiceChannel.join (/app/node_modules/discord.js/src/structures/VoiceChannel.js:130:30)
2019-07-02T19:34:43.765890+00:00 app[worker.1]:     at Object.Audio.connectToVoice (/app/bot.js:1414:31)`

Tried everything, not fixable for me

**Comment by zachdoug24** [comment]
FFMPEG is not an issue with our modifications, that is something that is present in DBM itself. This repository is only for beta modifications that are user madem

**Comment by YordiYVE** [comment]
There is no music outside of the beta so I don't see it having anything to do with stable.
