### ISSUE TITLE
SQL Query Not Work

### ISSUE THREAD

**Issue by GameHQ702** [Discord-Bot-Maker-Mods/DBM-Mods#230]
Error:
```
DBM MODS (Node Module Installer v2.1) Attempting To Install Node Module: 'sequelize'. Please wait...
DBM MODS (Node Module Installer v2.1): Node Module 'sequelize' does not exist!
Command failed: npm install sequelize --loglevel=error --save
DBM MODS (Node Module Installer v2.1) Attempting To Install Node Module: 'mysql2'. Please wait...
DBM MODS (Node Module Installer v2.1): Node Module 'mysql2' does not exist!
Command failed: npm install mysql2 --loglevel=error --save
DBM MODS (Node Module Installer v2.1) Attempting To Install Node Module: 'pg-hstore'. Please wait...
DBM MODS (Node Module Installer v2.1): Node Module 'pg-hstore' does not exist!
Command failed: npm install pg-hstore --loglevel=error --save
DBM MODS (Node Module Installer v2.1) Attempting To Install Node Module: 'tedious'. Please wait...
DBM MODS (Node Module Installer v2.1): Node Module 'tedious' does not exist!
Command failed: npm install tedious --loglevel=error --save
DBM MODS (Node Module Installer v2.1) Attempting To Install Node Module: 'sqlite3'. Please wait...
DBM MODS (Node Module Installer v2.1): Node Module 'sqlite3' does not exist!
Command failed: npm install sqlite3 --loglevel=error --save
SQL Mod Error: Error: Cannot find module 'sequelize' at Function.Module._resolveFilename (module.js:509:15) at Function.Module._load (module.js:456:25) at Module.require (module.js:537:17) at require (internal/module.js:11:18) at Object.action [as Run SQL Query] (E:\Downloads\MegaSyncDownloads\Discord.Bot.Maker\Discord.Bot.Maker\Discord Bot Maker\actions\run_sql_query_MOD.js:495:31) at Object.Actions.invokeActions (E:\Documents\DiscordBots\Robounity Gen\js\Actions.js:139:18) at Object.Actions.preformActions (E:\Documents\DiscordBots\Robounity Gen\js\Actions.js:90:8) at Object.Bot.checkCommand (E:\Documents\DiscordBots\Robounity Gen\js\Bot.js:107:21) at Object.Bot.onMessage (E:\Documents\DiscordBots\Robounity Gen\js\Bot.js:90:13) at emitOne (events.js:115:13)
```

**Comment by Almeeida** [comment]
![](https://almeida.is-inside.me/lEQYxFY7.png)

**Comment by GameHQ702** [comment]
thx its works now
