### ISSUE TITLE
Some Errors Its Big Issue i think

### ISSUE THREAD

**Issue by NoobBotCreator** [Discord-Bot-Maker-Mods/DBM-Mods#42]
I made a Weather command
i ran the comamnd
And Then the happen
                                                ↓ No Modules In Your File!!!!

Error: Cannot find module 'yahoo-weather' 
    at Function.Module._resolveFilename (module.js:509:15)
    at Function.Module._load (module.js:456:25)
    at Module.require (module.js:537:17)
    at Object.WrexMODS.require (C:\Users\youar\Downloads\Discord.Bot.Maker\Discord.Bot.Maker\Discord Bot Maker\actions\aaa_wrexmods_dependencies_MOD.js:63:22)
    at Object.action [as Weather] (C:\Users\youar\Downloads\Discord.Bot.Maker\Discord.Bot.Maker\Discord Bot Maker\actions\weather_MOD.js:219:28)
    at Object.Actions.invokeActions (C:\Users\youar\Documents\新しいフォルダー (8)\ｻｯﾄﾘｰﾝ♪BOT\js\Actions.js:139:18)
    at Object.Actions.preformActions (C:\Users\youar\Documents\新しいフォルダー (8)\ｻｯﾄﾘｰﾝ♪BOT\js\Actions.js:90:8)
    at Object.Bot.checkCommand (C:\Users\youar\Documents\新しいフォルダー (8)\ｻｯﾄﾘｰﾝ♪BOT\js\Bot.js:107:21)
    at Object.Bot.onMessage (C:\Users\youar\Documents\新しいフォルダー (8)\ｻｯﾄﾘｰﾝ♪BOT\js\Bot.js:90:13)
    at emitOne (events.js:115:13)

**Comment by NoobBotCreator** [comment]
Please Fix it

**Comment by ChileanS** [comment]
npm install yahoo-weather in terminal

**Comment by iAmaury** [comment]
Or run the bot in your terminal then run the command.

**Comment by lucasboss45** [comment]
Shouldn't this be closed by now?

**Comment by LasseNiermann** [comment]
Yes
